---
- hosts: localhost
  become: yes
  gather_facts: false

  vars:

    USER: "1ohit"

  tasks:

  - name: Gather available local users
    getent:
      database: passwd

  - name: Show gathered local user names only
    debug:
      msg: "{{ item }}"
    loop: "{{ getent_passwd.keys() | list }}"
    when: ansible_check_mode

  - name: Check if local user account '{{ USER }}' exists
    assert:
      that:
        - USER in getent_passwd.keys()
      fail_msg: "Given user not exists!"
      success_msg: "Given user exists."
